// Generated by CoffeeScript 1.10.0
(function() {
  var Database, EventEmitter, bookshelf, buildSchema, knex, uuid,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  bookshelf = require('bookshelf');

  knex = require('knex');

  uuid = require('uuid');

  EventEmitter = require('events').EventEmitter;

  buildSchema = require('./schema');

  Database = (function(superClass) {
    extend(Database, superClass);

    function Database(config) {
      this.config = config;
      this.knex = knex(this.config);
      this.bookshelf = bookshelf(this.knex);
      this.ready = false;
      this.models = require('./models')(this.bookshelf);
      if (this.knex.client === 'sqlite3') {
        this.knex.raw('PRAGMA foreign_keys = ON;');
      }
      buildSchema(this.knex).then((function(_this) {
        return function() {
          console.log('Database initialized');
          _this.ready = true;
          return _this.emit('ready');
        };
      })(this))["catch"](function(err) {
        return console.error('Database initialization failed', err);
      });
    }

    Database.prototype.genAPIKey = function() {
      var key;
      key = new Buffer(16);
      uuid.v4(null, key);
      return key.toString('base64');
    };

    Database.prototype.genFileHash = function(name) {
      var alphabet, code, hash, ts;
      alphabet = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
      hash = function(str) {
        var h, i, x;
        h = 0;
        for (i in str) {
          x = str.charCodeAt(i);
          h = x + (h << 6) + (h << 16) - h;
        }
        return h & 0x7fffffff;
      };
      ts = Date.now();
      ts = (ts << 1) + (hash(name) % ts);
      ts = Math.abs(ts);
      code = '';
      while (ts > 0) {
        code += alphabet[ts % alphabet.length];
        ts = Math.floor(ts / alphabet.length);
      }
      return code;
    };

    Database.prototype.addUser = function() {
      var User;
      if (!this.ready) {
        throw new Error('Database has not been initialized yet');
      }
      User = this.models.User;
      return User.forge({
        key: this.genAPIKey()
      }).save().tap((function(_this) {
        return function(user) {
          return _this.emit('newuser', user.attributes);
        };
      })(this));
    };

    Database.prototype.addImage = function(file, uploader_key) {
      var Image, data;
      if (uploader_key == null) {
        uploader_key = null;
      }
      data = {
        filename: [this.genFileHash(file.filename), file.extension].join('.'),
        expires: Date.now() + file.expiration
      };
      if (uploader_key) {
        data.user_key = uploader_key;
      }
      Image = this.models.Image;
      return Image.forge(data).save().tap((function(_this) {
        return function(image) {
          return _this.emit('newimage', image.attributes);
        };
      })(this));
    };

    return Database;

  })(EventEmitter);

  module.exports = Database;

}).call(this);
