// Generated by CoffeeScript 1.9.0
(function() {
  module.exports = function(bookshelf) {
    var Image, User;
    Image = bookshelf.Model.extend({
      tableName: 'images',
      initialize: function() {
        return this.on('creating', (function(_this) {
          return function() {
            return _this.set('created_at', new Date());
          };
        })(this));
      }
    }, {
      owner: function() {
        return this.belongsTo(User, 'user_key');
      }
    });
    User = bookshelf.Model.extend({
      tableName: 'users',
      initialize: function() {
        return this.on('creating', (function(_this) {
          return function() {
            return _this.set('created_at', new Date());
          };
        })(this));
      }
    }, {
      images: function() {
        return this.hasMany(Image, 'user_key');
      }
    });
    return {
      Image: Image,
      User: User
    };
  };

}).call(this);
