// Generated by CoffeeScript 1.10.0
(function() {
  var Promise, TABLES;

  Promise = require('bluebird');

  TABLES = {
    images: function(t) {
      t.increments('id').primary();
      t.string('filename', 20).unique();
      t.string('user_key').references('users.key').onDelete('set null').index();
      t.dateTime('expires').index();
      return t.timestamp('created_at');
    },
    users: function(t) {
      t.increments('id').primary();
      t.string('key', 24).unique();
      return t.timestamp('created_at');
    }
  };

  module.exports = function(knex) {
    return Promise.all(Object.keys(TABLES).map(function(table) {
      return knex.schema.hasTable(table).then(function(exists) {
        if (!exists) {
          console.log('Creating table %s', table);
          return knex.schema.createTable(table, TABLES[table]);
        } else {
          return true;
        }
      });
    }));
  };

}).call(this);
