// Generated by CoffeeScript 1.10.0
(function() {
  var Configuration, DEFAULT, path;

  path = require('path');

  DEFAULT = {
    db: {
      client: 'sqlite3',
      connection: {
        filename: path.resolve(__dirname, '..', 'snap.sqlite')
      }
    },
    allowedMimeTypes: {
      'image/bmp': 'bmp',
      'image/gif': 'gif',
      'image/jpeg': 'jpg',
      'image/png': 'png',
      'image/webp': 'webp',
      'image/svg+xml': 'svg',
      'video/webm': 'webm'
    },
    maxFileSize: 8 * 1024 * 1024,
    uploadDir: path.resolve(__dirname, '..', 'uploads'),
    storageDir: path.resolve(__dirname, '..', 'im'),
    basePath: '/',
    allowAnonymousUploads: false,
    authHeader: 'x-simplesnap-auth',
    expirationLimit: 30 * 24 * 60 * 60 * 1000,
    deleteExpiredInterval: 10 * 60 * 1000,
    bindAddresses: [['', 5000]]
  };

  Configuration = (function() {
    function Configuration(config) {
      var key, val;
      for (key in DEFAULT) {
        val = DEFAULT[key];
        this[key] = val;
      }
    }

    return Configuration;

  })();

  module.exports = Configuration;

}).call(this);
