// Generated by CoffeeScript 1.7.1
(function() {
  var Configuration, DEFAULT, path;

  path = require('path');

  DEFAULT = {
    db: {
      client: 'sqlite3',
      connection: {
        filename: path.resolve(__dirname, '..', 'snap.sqlite')
      }
    },
    allowedMimeTypes: {
      'image/bmp': 'bmp',
      'image/gif': 'gif',
      'image/jpeg': 'jpg',
      'image/png': 'png'
    },
    maxFileSize: 8 * 1024 * 1024,
    storageDir: path.resolve(__dirname, '..', 'im'),
    basePath: '/',
    allowAnonymousUploads: false,
    bindAddresses: [['0.0.0.0', 5000]]
  };

  Configuration = (function() {
    function Configuration(config) {
      var key, val;
      this.config = {};
      for (key in DEFAULT) {
        val = DEFAULT[key];
        this.config[key] = val;
      }
    }

    Configuration.prototype.getDatabaseConfiguration = function() {
      return this.config.db;
    };

    return Configuration;

  })();

  module.exports = Configuration;

}).call(this);
