// Generated by CoffeeScript 1.8.0
(function() {
  var Application, Configuration, Database, app, config, db, fs, path, userConfigFile, _ref, _ref1, _ref2;

  fs = require('fs');

  path = require('path');

  Configuration = require('./configuration');

  Database = require('./db/database');

  Application = require('./web/application');

  config = new Configuration();

  db = new Database(config.db);

  userConfigFile = path.join(__dirname, '..', 'config.js');

  if (fs.existsSync(userConfigFile)) {
    require(userConfigFile)(config);
  }

  if (!fs.existsSync(config.uploadDir)) {
    fs.mkdirSync(config.uploadDir);
  }

  if (!fs.existsSync(config.storageDir)) {
    fs.mkdirSync(config.storageDir);
  }

  if (process.argv.length > 2) {
    if ((_ref = process.argv[2]) === '--adduser' || _ref === '-a') {
      db.on('ready', function() {
        return db.addUser().then(function(user) {
          console.log('Created user', JSON.stringify(user.attributes));
          return process.exit(0);
        })["catch"](function(err) {
          console.error('Error creating user', err);
          return process.exit(-1);
        });
      });
    } else if ((_ref1 = process.argv[2]) === '--listusers' || _ref1 === '-l') {
      db.on('ready', function() {
        var User;
        User = db.models.User;
        return User.fetchAll().then(function(users) {
          users = users.map(function(user) {
            return JSON.stringify(user.attributes);
          });
          users.forEach(function(user) {
            return console.log(user);
          });
          return process.exit(0);
        })["catch"](function(err) {
          console.error('Error listing users', err);
          return process.exit(-1);
        });
      });
    } else if ((_ref2 = process.argv[2]) === '--revokeuser' || _ref2 === '-r') {
      if (process.argv.length < 4) {
        console.error("Usage: node " + process.argv[1] + " --revokeuser <user key>");
        process.exit(-1);
      }
      db.on('ready', function() {
        var User;
        User = db.models.User;
        return User.forge({
          key: process.argv[3]
        }).fetch({
          require: true
        }).then(function(user) {
          var key;
          key = user.get('key');
          return user.destroy();
        }).then(function() {
          console.log("Deleted user " + process.argv[3]);
          return process.exit(0);
        })["catch"](function(err) {
          console.error('Deletion failed', err);
          return process.exit(-1);
        });
      });
    }
  } else {
    console.log('Initializing webserver');
    app = new Application(config, db);
    console.log('Starting delete expired images task');
    require('./expiretask')(config, db);
  }

}).call(this);
