// Generated by CoffeeScript 1.7.1
(function() {
  var Application, Configuration, Database, app, config, db, fs, winston, _ref, _ref1;

  fs = require('fs');

  winston = require('winston');

  Configuration = require('./configuration');

  Database = require('./db/database');

  Application = require('./web/application');

  config = new Configuration();

  db = new Database(config.db);

  if (!fs.existsSync(config.uploadDir)) {
    fs.mkdirSync(config.uploadDir);
  }

  if (!fs.existsSync(config.storageDir)) {
    fs.mkdirSync(config.storageDir);
  }

  if (process.argv.length > 2) {
    if ((_ref = process.argv[2]) === '--adduser' || _ref === '-a') {
      db.on('ready', function() {
        return db.addUser().then(function(user) {
          winston.info('Created user', JSON.stringify(user.attributes));
          return process.exit(0);
        })["catch"](function(err) {
          return winston.error('Error creating user', err);
        });
      });
    } else if ((_ref1 = process.argv[2]) === '--listusers' || _ref1 === '-l') {
      db.on('ready', function() {
        var User;
        User = db.models.User;
        return User.fetchAll().then(function(users) {
          users = users.map(function(user) {
            return JSON.stringify(user.attributes);
          });
          users.forEach(function(user) {
            return winston.info(user);
          });
          return process.exit(0);
        })["catch"](function(err) {
          return winston.error('Error listing users', err);
        });
      });
    }
  } else {
    winston.info('Initializing webserver');
    app = new Application(config, db);
  }

}).call(this);
