// Generated by CoffeeScript 1.9.0
(function() {
  var Configuration, Database, Datastore, Promise, fs, main, path;

  fs = require('fs');

  path = require('path');

  Promise = require('bluebird');

  Datastore = require('nedb');

  Configuration = require('./configuration');

  Database = require('./db/database');

  main = function() {
    var config, db, neImages;
    config = new Configuration();
    if (fs.existsSync(path.join(__dirname, '..', 'config.js'))) {
      require(path.join(__dirname, '..', 'config.js'))(config);
    }
    db = new Database(config.db);
    neImages = new Datastore({
      filename: path.join(__dirname, '..', 'images.db')
    });
    neImages.loadDatabase();
    return db.on('ready', function() {
      var Image;
      Image = db.models.Image;
      return neImages.find({}, function(err, docs) {
        if (err) {
          console.error(err);
          process.exit(-1);
        }
        return Promise.all(docs.map(function(doc) {
          return Image.forge({
            filename: doc.path.replace(/^\//, ''),
            expires: doc.expires
          }).save().tap(function(image) {
            return console.log("Migrated " + (image.get('filename')));
          });
        })).then(function() {
          console.log('Successful import');
          console.log('Verify that the database was imported correctly and then it is safe to remove images.db');
          return process.exit(0);
        })["catch"](function(err) {
          console.error(err);
          return process.exit(-1);
        });
      });
    });
  };

  main();

}).call(this);
