// Generated by CoffeeScript 1.10.0
(function() {
  var Application, BAD_REQUEST, INTERNAL_SERVER_ERROR, NOT_FOUND, Promise, express, fs, ms, path,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  express = require('express');

  path = require('path');

  ms = require('ms');

  Promise = require('bluebird');

  fs = Promise.promisifyAll(require('fs'));

  BAD_REQUEST = 400;

  NOT_FOUND = 404;

  INTERNAL_SERVER_ERROR = 500;

  Application = (function() {
    function Application(config, db) {
      var basePath, ext, extensions, host, i, imagePath, len, mime, port, ref, ref1;
      this.config = config;
      this.db = db;
      this.deleteImage = bind(this.deleteImage, this);
      this.uploadImage = bind(this.uploadImage, this);
      this.serveImage = bind(this.serveImage, this);
      this.serveImageList = bind(this.serveImageList, this);
      this.getFullImagePath = bind(this.getFullImagePath, this);
      this.app = express();
      this.app.use(require('./authorization')(this.config, this.db));
      this.app.use(require('./fileparser')(this.config));
      this.app.use(require('./detectmime')(this.config));
      extensions = ((function() {
        var ref, results;
        ref = this.config.allowedMimeTypes;
        results = [];
        for (mime in ref) {
          ext = ref[mime];
          results.push(ext);
        }
        return results;
      }).call(this)).join('|');
      basePath = this.config.basePath.replace(/\//g, '\\/');
      imagePath = basePath + "([a-zA-Z0-9]+\.(?:" + extensions + "))";
      this.app.get(new RegExp(imagePath), this.serveImage);
      this.app["delete"](new RegExp(imagePath), this.deleteImage);
      this.app.post(this.config.basePath + "upload", this.uploadImage);
      this.app.put(this.config.basePath + "upload", this.uploadImage);
      this.app.get(this.config.basePath + "images", this.serveImageList);
      this.app.get(this.config.basePath, this.serveIndex);
      this.app.use(this.errorHandler);
      ref = this.config.bindAddresses;
      for (i = 0, len = ref.length; i < len; i++) {
        ref1 = ref[i], host = ref1[0], port = ref1[1];
        this.app.listen(port, host);
      }
    }

    Application.prototype.getProtocol = function(req) {
      var ref;
      if (((ref = req.ip) === '127.0.0.1' || ref === '::1') && req.header('x-forwarded-proto')) {
        return req.header('x-forwarded-proto');
      } else {
        return req.protocol;
      }
    };

    Application.prototype.getFullImagePath = function(req, filename) {
      var filepath;
      filepath = this.config.basePath + filename;
      return (this.getProtocol(req)) + "://" + (req.header('host')) + filepath;
    };

    Application.prototype.serveImageList = function(req, res) {
      var Image;
      if (req.header(this.config.authHeader)) {
        Image = this.db.models.Image;
        return Image.where({
          user_key: req.header(this.config.authHeader)
        }).fetchAll().then((function(_this) {
          return function(images) {
            var elems;
            elems = images.map(function(image) {
              return _this.getFullImagePath(req, image.get('filename'));
            });
            return res.json({
              images: elems
            });
          };
        })(this));
      } else {
        return res.json({
          error: "No " + this.config.authHeader + " header present"
        });
      }
    };

    Application.prototype.serveIndex = function(req, res) {
      var html;
      html = "<!doctype html>\n<html>\n    <head>\n        <title>Simplesnap</title>\n        <meta charset=\"utf-8\">\n    </head>\n    <body>\n        This server is running <a href=\"https://github.com/calzoneman/simplesnap\">simplesnap</a>.\n    </body>\n</html>";
      return res.send(html);
    };

    Application.prototype.serveImage = function(req, res) {
      return res.sendFile(req.params[0], {
        root: this.config.storageDir
      });
    };

    Application.prototype.uploadImage = function(req, res) {
      var data, delay, file, limit;
      if (!req.files.image) {
        return res.status(BAD_REQUEST).json({
          error: 'Expected image in request body'
        });
      }
      if (!req.body.expiration && this.config.expirationLimit > 0) {
        return res.status(BAD_REQUEST).json({
          error: 'Expiration is required'
        });
      }
      delay = null;
      if (req.body.expiration) {
        delay = ms(req.body.expiration);
        if (!delay) {
          return res.status(BAD_REQUEST).json({
            error: 'Invalid expiration'
          });
        } else if (this.config.expirationLimit > 0 && delay > this.config.expirationLimit) {
          limit = ms(this.config.expirationLimit);
          return res.status(BAD_REQUEST).json({
            error: "Expiration exceeds limit of " + limit
          });
        }
      }
      file = req.files.image;
      file.expiration = delay;
      data = null;
      return this.db.addImage(file, req.header(this.config.authHeader)).then((function(_this) {
        return function(image) {
          data = {
            filename: _this.getFullImagePath(req, image.get('filename')),
            expires: image.get('expires')
          };
          return fs.renameAsync(file.path, path.join(_this.config.storageDir, image.get('filename')));
        };
      })(this)).then(function() {
        return res.json(data);
      })["catch"](function(err) {
        res.status(INTERNAL_SERVER_ERROR).json({
          error: 'Unknown error'
        });
        return console.error('Upload failed:', err);
      });
    };

    Application.prototype.deleteImage = function(req, res) {
      var Image, filename;
      filename = req.params[0].replace(/^\//, '');
      Image = this.db.models.Image;
      return Image.forge({
        filename: filename
      }).fetch({
        require: true
      }).tap((function(_this) {
        return function(image) {
          return fs.unlinkAsync(path.join(_this.config.storageDir, filename));
        };
      })(this)).then(function(image) {
        return image.destroy();
      }).then((function(_this) {
        return function() {
          return res.json({
            deleted: _this.getFullImagePath(req, filename)
          });
        };
      })(this))["catch"](Image.NotFoundError, function(err) {
        return res.status(404).json({
          error: 'Image not found'
        });
      })["catch"](function(err) {
        res.status(INTERNAL_SERVER_ERROR).json({
          error: 'Unknown error'
        });
        return console.error('Deletion failed', err);
      });
    };

    Application.prototype.errorHandler = function(err, req, res, next) {
      var method;
      method = req.method.toLowerCase();
      if (err.code === 'ENOENT') {
        return res.sendStatus(NOT_FOUND);
      } else {
        console.error('HTTP Server Error', err);
        return res.status(INTERNAL_SERVER_ERROR).json({
          error: 'Internal server error'
        });
      }
    };

    return Application;

  })();

  module.exports = Application;

}).call(this);
