// Generated by CoffeeScript 1.10.0
(function() {
  var UNAUTHORIZED;

  UNAUTHORIZED = 401;

  module.exports = function(config, db) {
    return function(req, res, next) {
      var User, ref;
      if ((ref = req.method.toLowerCase()) !== 'post' && ref !== 'put' && ref !== 'delete') {
        return next();
      }
      if (!req.header(config.authHeader)) {
        if (config.allowAnonymousUploads) {
          return next();
        } else {
          res.status(UNAUTHORIZED).json({
            error: "Missing " + config.authHeader + " header"
          });
          return req.destroy();
        }
      }
      User = db.models.User;
      return User.forge({
        key: req.header(config.authHeader)
      }).fetch({
        require: true
      }).then(function(user) {
        req.user = user;
        return next();
      })["catch"](function(err) {
        res.status(UNAUTHORIZED).json({
          error: "Invalid " + config.authHeader + " ID"
        });
        return req.destroy();
      });
    };
  };

}).call(this);
