// Generated by CoffeeScript 1.7.1
(function() {
  var UNAUTHORIZED;

  UNAUTHORIZED = 401;

  module.exports = function(config, db) {
    return function(req, res, next) {
      var User, _ref;
      if ((_ref = req.method.toLowerCase()) !== 'post' && _ref !== 'put' && _ref !== 'delete') {
        return next();
      }
      if (!req.header(config.authHeader)) {
        if (config.allowAnonymousUploads()) {
          next();
        } else {
          res.status(UNAUTHORIZED);
          req.destroy();
        }
      }
      User = db.models.User;
      return User.forge({
        key: req.header(config.authHeader)
      }).fetch({
        require: true
      }).then(function(user) {
        req.user = user;
        return next();
      })["catch"](function(err) {
        res.status(UNAUTHORIZED);
        return req.destroy();
      });
    };
  };

}).call(this);
