// Generated by CoffeeScript 1.9.0
(function() {
  var INTERNAL_SERVER_ERROR, Magic, UNSUPPORTED_MEDIA_TYPE, mmmagic;

  mmmagic = require('mmmagic');

  Magic = mmmagic.Magic;

  UNSUPPORTED_MEDIA_TYPE = 415;

  INTERNAL_SERVER_ERROR = 500;

  module.exports = function(config) {
    return function(req, res, next) {
      var file, magic;
      if (!req.files || !req.files.image) {
        return next();
      }
      magic = new Magic(mmmagic.MAGIC_MIME_TYPE);
      file = req.files.image;
      return magic.detectFile(file.path, function(err, mime) {
        if (err) {
          res.status(INTERNAL_SERVER_ERROR).json({
            error: 'Failed to detect mime type of image'
          });
          req.destroy();
          return console.error('Failed to detect mime type for %s: %s', file, err);
        } else if (!(mime in config.allowedMimeTypes)) {
          res.status(UNSUPPORTED_MEDIA_TYPE).json({
            error: "Illegal mime type " + mime
          });
          return req.destroy();
        } else {
          file.mime = mime;
          file.extension = config.allowedMimeTypes[mime];
          return next();
        }
      });
    };
  };

}).call(this);
