// Generated by CoffeeScript 1.7.1
(function() {
  var REQUEST_ENTITY_TOO_LARGE, multiparty;

  multiparty = require('multiparty');

  REQUEST_ENTITY_TOO_LARGE = 413;

  module.exports = function(config) {
    return function(req, res, next) {
      var form, _ref;
      if ((_ref = req.method.toLowerCase()) !== 'post' && _ref !== 'put') {
        return next();
      }
      form = new multiparty.Form({
        autoFiles: true,
        uploadDir: config.uploadDir
      });
      form.on('progress', function(bytesReceived, bytesExpected) {
        if (bytesReceived > config.maxFileSize || bytesExpected > config.maxFileSize) {
          res.status(REQUEST_ENTITY_TOO_LARGE);
          return req.destroy();
        }
      });
      return form.parse(req, function(err, fields, files) {
        var key, value;
        if (err) {
          return next(err);
        }
        req.files = files;
        for (key in fields) {
          value = fields[key];
          req.body[key] = fields[key][0];
        }
        return next();
      });
    };
  };

}).call(this);
